# Generated by Django 3.1.3 on 2020-11-18 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20201118_1908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitation',
            old_name='time',
            new_name='invited_on',
        ),
    ]
