# Generated by Django 3.1.3 on 2020-11-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwithtitle',
            name='channel_id',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
