# Generated by Django 3.1.1 on 2020-09-19 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibit',
            name='info',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='posx',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='posy',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='posz',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='exhibit',
            name='roty',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
