# Generated by Django 3.1.3 on 2020-11-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0003_auto_20201121_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwithtitle',
            name='consumer',
            field=models.CharField(blank=True, max_length=96),
        ),
    ]
