# Generated by Django 3.1.2 on 2020-10-31 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0003_useractivity_dnd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibit',
            name='info',
            field=models.TextField(max_length=487),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='name',
            field=models.CharField(max_length=38),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='summary',
            field=models.TextField(max_length=121),
        ),
    ]
