# Generated by Django 3.1.3 on 2020-11-25 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0004_userwithtitle_consumer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userwithtitle',
            name='last_activity_date',
        ),
    ]
