# Generated by Django 3.1.2 on 2020-10-31 15:51

import annoying.fields
from django.conf import settings
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0004_auto_20201031_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='id',
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='user',
            field=annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
