# Generated by Django 3.1.2 on 2020-10-31 18:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0005_auto_20201031_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwithtitle',
            name='dnd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userwithtitle',
            name='last_activity_date',
            field=models.DateTimeField(default=datetime.datetime(1950, 1, 1, 0, 0)),
        ),
    ]
