# Generated by Django 3.1.2 on 2020-10-31 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0005_exhibit_hash'),
        ('exhibition', '0006_auto_20201031_1812'),
    ]

    operations = [
    ]
