# Generated by Django 3.1.2 on 2020-10-31 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0008_auto_20201031_1847'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserActivity',
        ),
    ]
