# Generated by Django 3.1.2 on 2020-10-31 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0009_delete_useractivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userwithtitle',
            name='dnd',
        ),
        migrations.AddField(
            model_name='userwithtitle',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('dnd', 'Dnd')], default='offline', max_length=7),
        ),
    ]
